### ISSUE TITLE
Crash: NullPointerException in CaveListWrapper.getCenterScore()

### ISSUE THREAD

**Issue by ColorYak** [WhiskyTangoFawks/Expedition#100]
MC quit shortly after creating a new world. It might be caused by setting RTG's dungeon occurence rate and cave size too high, but it's a guess.

Log: https://gist.github.com/ColorYak/954d0e4d9324af253665c5b20633f1e8

I think the interesting part is here:

```
Caused by: java.lang.NullPointerException
	at wtf.utilities.wrappers.CaveListWrapper.getCenterScore(CaveListWrapper.java:177) ~[CaveListWrapper.class:?]
	at wtf.utilities.wrappers.CaveListWrapper.dungeonScore(CaveListWrapper.java:253) ~[CaveListWrapper.class:?]
	at wtf.worldgen.DungeonPopulator.getLargestCave(DungeonPopulator.java:115) ~[DungeonPopulator.class:?]
	at wtf.worldgen.DungeonPopulator.generate(DungeonPopulator.java:40) ~[DungeonPopulator.class:?]
```

Am not really sure what's going on, but it's a position that's missing in the first stack entry, and before the second entry(CaveListWrapper.java:253) we have this comment:

```//and because it we just did check center, we know that pos can't == null```

**Comment by WhiskyTangoFawks** [comment]
I just released an alpha with an architectural overhaul of the generation system.  Let me know if you're still able to get this crash.

**Comment by ColorYak** [comment]
Thank you for the quick reply. I will reopen the issue if I encounter it.

BTW I loved your mods for 1.7.10; they really improved the survival experience. I am excited to try out Expedition.
