### ISSUE TITLE
Crash Entering the End

### ISSUE THREAD

**Issue by An-Sar** [WhiskyTangoFawks/Expedition#108]
WTF-Expedition_1.10.2_v-1.4.1 and Forge 1.10.2-12.18.3.2234

Full Crash log:
http://pastebin.com/sU7SWPpH

`java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at wtf.worldscan.WorldScanner.getChunkScan(WorldScanner.java:85)
	at wtf.worldscan.CoreWorldGenListener.doChunk(CoreWorldGenListener.java:83)
	at wtf.worldscan.CoreWorldGenListener.doScanIfAdjArePopulated(CoreWorldGenListener.java:55)
	at wtf.worldscan.CoreWorldGenListener.populate(CoreWorldGenListener.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_CoreWorldGenListener_populate_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:619)
	at net.minecraft.world.gen.ChunkProviderEnd.func_185931_b(ChunkProviderEnd.java:392)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by WhiskyTangoFawks** [comment]
New version's out, should fix the issue.
