### ISSUE TITLE
Crash on entering End

### ISSUE THREAD

**Issue by Aschy2** [WhiskyTangoFawks/Expedition#110]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.1-70.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/27/17 6:11 PM
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at wtf.worldscan.WorldScanner.getChunkScan(WorldScanner.java:85)
	at wtf.worldscan.CoreWorldGenListener.doChunk(CoreWorldGenListener.java:83)
	at wtf.worldscan.CoreWorldGenListener.doScanIfAdjArePopulated(CoreWorldGenListener.java:55)
	at wtf.worldscan.CoreWorldGenListener.populate(CoreWorldGenListener.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_288_CoreWorldGenListener_populate_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:619)
	at net.minecraft.world.gen.ChunkProviderEnd.func_185931_b(ChunkProviderEnd.java:392)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at wtf.worldscan.WorldScanner.getChunkScan(WorldScanner.java:85)
	at wtf.worldscan.CoreWorldGenListener.doChunk(CoreWorldGenListener.java:83)
	at wtf.worldscan.CoreWorldGenListener.doScanIfAdjArePopulated(CoreWorldGenListener.java:55)
	at wtf.worldscan.CoreWorldGenListener.populate(CoreWorldGenListener.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_288_CoreWorldGenListener_populate_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:619)
	at net.minecraft.world.gen.ChunkProviderEnd.func_185931_b(ChunkProviderEnd.java:392)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:974)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
	Level name: New World-
	All players: 1 total; [EntityPlayerMP['Aschy'/445, l='New World-', x=100.00, y=50.00, z=0.00]]
	Chunk stats: ServerChunkCache: 21 Drop: 0
	Level seed: -2163303121567223929
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1463206784 bytes (1395 MB) / 2959667200 bytes (2822 MB) up to 4085252096 bytes (3896 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2000M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	babymobs{1.5.4} [Baby Mobs] (BabyMobs-1.10.2-1.5.4.jar) 
	UCHIJAAAA	XaeroBetterPvP{1.11.4} [Better PVP Mod] (BetterPvP_1.11.4_Forge_1.10.2.jar) 
	UCHIJAAAA	betterquesting{2.3.217} [Better Questing] (BetterQuesting-2.3.217.jar) 
	UCHIJAAAA	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(20nov16).jar) 
	UCHIJAAAA	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCHIJAAAA	tem{2.3.10} [Tim's Expansion Mod] (ExpansionMod-2.3.10(MC1.10.2).jar) 
	UCHIJAAAA	JEI{3.12.7.312} [Just Enough Items] (jei_1.10.2-3.12.7.312.jar) 
	UCHIJAAAA	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (Light-Level-Overlay-Reloaded-Mod-1.10.2.jar) 
	UCHIJAAAA	FEI{1.0.16} [Forever Enough Items] (ForeverEnoughItems-1.0.16-1.10.2.jar) 
	UCHIJAAAA	gemcraft{1.2.5} [Gem Craft] (gemcraft-1.10.2-1.2.5.jar) 
	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.6-1.10.2.jar) 
	UCHIJAAAA	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCHIJAAAA	bq_npc_integration{2.3.19} [NPC Integration] (NPCIntegration-2.3.19.jar) 
	UCHIJAAAA	bq_rf{2.3.24} [RF Expansion] (RFExpansion-2.3.24.jar) 
	UCHIJAAAA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCHIJAAAA	spartanshields{1.1b} [Spartan Shields] (SpartanShields-1.10.2-1.1b.jar) 
	UCHIJAAAA	bq_standard{2.3.124} [Standard Expansion] (StandardExpansion-2.3.124.jar) 
	UCHIJAAAA	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCHIJAAAA	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCHIJAAAA	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCHIJAAAA	examplemod{1.0} [examplemod] (WTF-Expedition_1.10.2_v-1.4.jar) 
	UCHIJAAAA	wtfcore{1.10.2_v1.4} [WTFs-Expedition] (WTF-Expedition_1.10.2_v-1.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Aschy'/445, l='New World-', x=100.00, y=50.00, z=0.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by WhiskyTangoFawks** [comment]
Updating to the latest beta fixes this issue.
