### ISSUE TITLE
No ores or cave decorations

### ISSUE THREAD

**Issue by Octopork** [WhiskyTangoFawks/Expedition#111]
Version 1.5 beta 2 

Not getting any of your mods world gen in the newest beta, someone reported the same issue on the forum  

snippet to get the idea.
```
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at wtf.worldgen.GeneratorMethods.<init>(GeneratorMethods.java:110)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at wtf.worldgen.MultiThreadScanner.run(MultiThreadScanner.java:52)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:745)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[12:47:28] [pool-4-thread-1/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 5 more
```

full log: http://pastebin.com/Beyy17Eb

**Comment by Octopork** [comment]
Bingo!

damn you accidental Scala imports!!!

wtf.ores.OreReplacer.java

just switch it over to java.util.random instead of scala.util.random

Works perfectly for me now, obviously not making a pull request as it would just be more time consuming to fix than just doing yourself.

**Comment by WhiskyTangoFawks** [comment]
New release just went out that solves this issue, and the world gen crash in the last version I released while trying to solve this issue quickly and not testing sufficiently.
