### ISSUE TITLE
Crash!!!

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [WhiskyTangoFawks/Expedition#125]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 3/19/17 3:43 PM
Description: Initializing game

java.lang.NullPointerException: at index 0
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)
	at net.minecraft.client.resources.ResourcePackRepository.func_110613_c(SourceFile:176)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:743)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)
	at net.minecraft.client.resources.ResourcePackRepository.func_110613_c(SourceFile:176)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:743)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 179787680 bytes (171 MB) / 374341632 bytes (357 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 Optifine OptiFine_1.10.2_HD_U_D6 15 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJA	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	appalachia{0.1.0-UNSTABLE-ALPHA-4} [Appalachia] (Appalachia-1.10.2-0.1.0-UNSTABLE-ALPHA-4.jar) 
	UCHIJA	atg{2} [Alternate Terrain Generation] (atg-1.10.2-2.0.1.jar) 
	UCHIJA	BiomeTweaker{2.1.230} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.230.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2162} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2162-universal.jar) 
	UCHIJA	BiomesYouGo{4.1.0} [BiomesYouGo] (BiomesYouGo (Version 4.1.0).jar) 
	UCHIJA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
	UCHIJA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJA	SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-MC1.10-1.3.jar) 
	UCHIJA	wtfcore{1.10.2_v1.5} [WTFs Expedition] (WTF-Expedition-WorldGen_1.10.2_-1.5beta.jar) 
	UD	BiomeTweakerCore{2.1.230} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 610/PCIe/SSE2'
	Launched Version: HMCL 2.7.4.13
	LWJGL: 2.9.4
	OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU G3250 @ 3.20GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_D6
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0
	OpenGlRenderer: GeForce GT 610/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2

**Comment by WhiskyTangoFawks** [comment]
I'm pretty sure this is the standard first load crash that's a result of the blockstate resource pack writer.  As long as it doesn't happen again, you can safely ignore it.

**Comment by mgdgfbhevdyeh** [comment]
thx!
