### ISSUE TITLE
Custom mod blocks can have issues breaking [1.10.2][Expedition: Gameplay]

### ISSUE THREAD

**Issue by shadowbolt79** [WhiskyTangoFawks/Expedition#144]
I have been adding in mod ores into this pack I'm making for myself and friends to play. MOST ores work fine, but there have been a few ores that when broken, they disappear client side until right clicked. Does not happen without Gameplay installed. Tracked it down to an error within block breaking:

`[13:05:54] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@6f09097d:
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_25]
	at wtf.fracturing.EntityStoneCrack.crackOre(EntityStoneCrack.java:88) ~[EntityStoneCrack.class:?]
	at wtf.fracturing.EntityStoneCrack.FracOre(EntityStoneCrack.java:64) ~[EntityStoneCrack.class:?]
	at wtf.eventlisteners.ListenerOreFrac.BlockBreakEvent(ListenerOreFrac.java:46) ~[ListenerOreFrac.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_964_ListenerOreFrac_BlockBreakEvent_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:742) [ForgeHooks.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:287) [lv.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180785_a(PlayerInteractionManager.java:248) [lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:642) [me.class:?]
	at ValkyrienWarfareBase.Interaction.CustomNetHandlerPlayServer.func_147345_a(CustomNetHandlerPlayServer.java:132) [Valkyrien%20Warfare%200.9_pre_1.jar:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [ja.class:?]
	at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [ja.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
`

**Comment by ThatScar** [comment]
The issue still stands and is awfully annoying. A crude work-around is to **use simplified fracturing** because that mode doesn't trigger this one `Random.nextInt` line that makes it broken, desynced or even crashes the game.
EDIT: forgot to mention, it's not only custom mods, I've tried making Sand Ore, Sponge Ore and Glass Ore for testing and sand worked but sponge and glass threw this very error. After enabling simple fracturing mode, sponge now works and glass works-ish but it doesn't drop, I guess you need a tool that can mine both stone and glass? (hardly a problem, all ores from all mods are mined with pickaxes)
