### ISSUE TITLE
NPE when accessing array of biome's trees in RTGCompat

### ISSUE THREAD

**Issue by srs-bsns** [WhiskyTangoFawks/Expedition#23]
You will need to add a null check on this array before trying to access it: https://github.com/WhiskyTangoFawks/Expedition/blob/master/1-9Forge/src/main/java/wtf/worldgen/trees/RTGCompat.java#L31

My assumption is that not every realistic biome has a custom tree array, so the array remains null for those biomes. @whichonespink44 would be able say for sure, since he wrote that code.

http://paste.ee/p/JqOQb

```
[00:19:13] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.terraingen.PopulateChunkEvent$Post@369dd772:
java.lang.NullPointerException
    at wtf.worldgen.trees.RTGCompat.getRTGTree(RTGCompat.java:32) ~[RTGCompat.class:?]
    at wtf.worldgen.RTGOverworldGen.getTree(RTGOverworldGen.java:47) ~[RTGOverworldGen.class:?]
    at wtf.worldgen.OverworldGen.genTrees(OverworldGen.java:109) ~[OverworldGen.class:?]
    at wtf.worldgen.RTGOverworldGen.genTrees(RTGOverworldGen.java:26) ~[RTGOverworldGen.class:?]
    at wtf.worldgen.OverworldGen.generate(OverworldGen.java:83) ~[OverworldGen.class:?]
    at wtf.worldscan.CoreWorldGenListener.doChunk(CoreWorldGenListener.java:85) ~[CoreWorldGenListener.class:?]
    at wtf.worldscan.CoreWorldGenListener.doScanIfAdjArePopulated(CoreWorldGenListener.java:58) ~[CoreWorldGenListener.class:?]
    at wtf.worldscan.CoreWorldGenListener.populate(CoreWorldGenListener.java:36) ~[CoreWorldGenListener.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_956_CoreWorldGenListener_populate_Post.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:589) [ForgeEventFactory.class:?]
    at rtg.world.gen.ChunkProviderRTG.doPopulate(ChunkProviderRTG.java:753) [ChunkProviderRTG.class:?]
    at rtg.world.gen.ChunkProviderRTG.clearDecorations(ChunkProviderRTG.java:766) [ChunkProviderRTG.class:?]
    at rtg.world.gen.ChunkProviderRTG.func_185931_b(ChunkProviderRTG.java:495) [ChunkProviderRTG.class:?]
```

**Comment by whichonespink44** [comment]
Here's the full log for reference: https://paste.ee/r/JqOQb

With regards to the crash... every RealisticBiome class gets an `rtgTrees` ArrayList by default, so the only way the NPE could be happening is if RTG is trying to generate a biome that it doesn't have a realistic version for, in which case it would be the `rb` from [this line](https://github.com/WhiskyTangoFawks/Expedition/blob/master/1-9Forge/src/main/java/wtf/worldgen/trees/RTGCompat.java#L30) that's being set to null.

Scanning the log reveals a few potential candidates:
```
[00:16:06] [Client thread/WARN]: [RTG-WARN] WARNING! RTG could not find a realistic version of Degraded (103) from org.cyclops.evilcraft.world.biome.BiomeDegraded. (If Degraded is a non-Overworld biome, then this is not an error.)
[00:16:06] [Client thread/WARN]: [RTG-WARN] WARNING! RTG could not find a realistic version of Autumn Forest (104) from net.minecraft.world.biome.BiomeForest. (If Autumn Forest is a non-Overworld biome, then this is not an error.)
[00:16:06] [Client thread/WARN]: [RTG-WARN] WARNING! RTG could not find a realistic version of Autumn Hills (105) from net.minecraft.world.biome.BiomeForest. (If Autumn Hills is a non-Overworld biome, then this is not an error.)
[00:16:06] [Client thread/WARN]: [RTG-WARN] WARNING! RTG could not find a realistic version of Storage Cell (106) from appeng.spatial.BiomeGenStorage. (If Storage Cell is a non-Overworld biome, then this is not an error.)
```
Assuming that 'Degraded' and 'Spatial Cell' are non-Overworld biomes, that leaves 'Autumn Forest' and 'Autumn Hills' as the likely suspects.

If those two Autumn X biomes have their own biome ID and they're being added to the list of biomes to generate in the Overworld, they're going to need a RealisticBiome associated with them.

@WhiskyTangoFawks Are those two biomes from Expedition? If so, you can add a RealisticBiome for them and inject them to the master array of biomes. This is how Appalachia does it as an example:

Create and add the biome configs:
https://github.com/Team-RTG/Appalachia/blob/1.10.2-dev/src/main/java/appalachia/Appalachia.java#L70-L71

Create and add the realistic biomes (which also require [Terrain and Surface](https://github.com/Team-RTG/Appalachia/blob/1.10.2-dev/src/main/java/appalachia/rtg/world/biome/realistic/appalachia/RealisticBiomeAPLBlueRidgeForest.java#L23-L24) classes):
https://github.com/Team-RTG/Appalachia/blob/1.10.2-dev/src/main/java/appalachia/Appalachia.java#L90

Having said all that, depending on what you're doing under the hood, it might be more desirable to just add a null check as @srs-bsns suggested.

**Comment by WhiskyTangoFawks** [comment]
The autumn biomes are mnine, but aren't added to the list of biomes to generate in the overworld, and are designed specifically to work with RTG anyway (they just redirect to the tree array of the parent biome- forest or forest hills).

**Comment by whichonespink44** [comment]
Nice one... I posted this on behalf of one of our Discord peeps, so I'll let him know that it should be fixed in the next release.

**Comment by WesCook** [comment]
Not sure when the next update will be released, so in the mean time will switching off `B:"Replace RTG Birch trees with custom large poplar trees"` prevent this crash from occurring?

I'm not sure if that's the feature that's leading to this issue or not.

**Comment by WhiskyTangoFawks** [comment]
This is an old issue that was fixed.  If you're getting it again, then I need to look into it, and I'll need a crash log to do so.

**Comment by WesCook** [comment]
My mistake, I assumed it was still active as the issue was open.  Next time it triggers I'll reply with a crash log.

**Comment by WesCook** [comment]
Looking at it closer, the error is different, but the same method is involved.

http://pastebin.com/tYg3sS7X

I should caution that I'm running Appalachia v0.1.0, which is in Alpha and considered unstable.  As that's an addon to RTG it may be related.
