### ISSUE TITLE
Crash on minecraft start up

### ISSUE THREAD

**Issue by Aschy2** [WhiskyTangoFawks/Expedition#99]
Hello, I'm creating a private mod pack and love how simple your ore generation config is but I have had it crash my game way more times then its done anything. I really need a COG and many of your features really improve the game. Plus will it work with custom dimensions I have not been able to figure that out yet.

PS. I hope you don't mind me using your mod pack.

Anyway my crash log is below. Here I'm trying to generate a custom ore in the nether. My goal is to generate 4 custom ores to the overworld, nether and a custom dimension.

Thanks for any help in advance
Aschy

"
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.1-70.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 2/10/17 12:53 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WTFs-Expedition (wtfcore)
Caused by: java.lang.NullPointerException
	at wtf.config.AbstractConfig.getBlockState(AbstractConfig.java:65)
	at wtf.config.ore.WTFOresNewConfig.loadConfig(WTFOresNewConfig.java:117)
	at wtf.Core.PreInit(Core.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1385274064 bytes (1321 MB) / 2019729408 bytes (1926 MB) up to 4085252096 bytes (3896 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn2000M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	babymobs{1.5.3} [Baby Mobs] (BabyMobs-1.10.2-1.5.3.jar) 
	UCH	XaeroBetterPvP{1.11.4} [Better PVP Mod] (BetterPvP_1.11.4_Forge_1.10.2.jar) 
	UCH	betterquesting{2.3.217} [Better Questing] (BetterQuesting-2.3.217.jar) 
	UCH	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCH	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCH	JEI{3.12.7.312} [Just Enough Items] (jei_1.10.2-3.12.7.312.jar) 
	UCH	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (Light-Level-Overlay-Reloaded-Mod-1.10.2.jar) 
	UCH	FEI{1.0.16} [Forever Enough Items] (ForeverEnoughItems-1.0.16-1.10.2.jar) 
	UCH	gemcraft{1.2.5} [Gem Craft] (gemcraft-1.10.2-1.2.5.jar) 
	UCH	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCH	levelup{${version}} [Level Up!] (LevelUp!-0.12.6-1.10.2.jar) 
	UCH	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCH	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.3-10.jar) 
	UCH	bq_rf{2.3.24} [RF Expansion] (RFExpansion-2.3.24.jar) 
	UCH	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.9-1.10.2.jar) 
	UCH	spartanshields{1.1b} [Spartan Shields] (SpartanShields-1.10.2-1.1b.jar) 
	UCH	bq_standard{2.3.124} [Standard Expansion] (StandardExpansion-2.3.124.jar) 
	UCH	beneath{1.2.0} [The Beneath] (The Beneath-1.10.2-1.2.0.jar) 
	UCH	ToughAsNails{1.0.11} [Tough As Nails] (ToughAsNails-1.9.4-1.0.11.jar) 
	UCH	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCH	examplemod{1.0} [examplemod] (WTF-Expedition_1.10.2_v-1.4.jar) 
	UCE	wtfcore{1.10.2_v1.4} [WTFs-Expedition] (WTF-Expedition_1.10.2_v-1.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 760/PCIe/SSE2'
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 760/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
"

**Comment by WhiskyTangoFawks** [comment]
You've made a mistake on the config.  It's trying to get a block based on a name you've supplied it, and the block doesn't exist, so it crashes.

**Comment by Aschy2** [comment]
Oh really? I was quite sure I had it right. Usually when it's not right it just would output in the config that it could not find the ore.

Ill try again, thanks for the tip!

And about the custom dimensions, can I just add a custom dimension ID to the config and it works?

**Comment by WhiskyTangoFawks** [comment]
It should, there was a bug a while back where it was ignoring that but I want to say the fix went out already

**Comment by Aschy2** [comment]
Okay great thanks, Ill dot my i's and cross my t's and let you know if I find anything.

**Comment by Aschy2** [comment]
Hey there WhiskyTangoFox,

Sorry to bother you again(I did on github) but I cannot figure this out, I'm not sure if this is the best place to discuss this if it isn't then let me know where you would like me to post it. Maybe I just don't understand the config well enough, and I understand if you shrug me off but I really could use a nudge in the right direction.. Anyway.. I'm struggling with the Custom Ore Generator, I want to spawn custom ores in dimension 1 and in a custom dimension which ID happens to be 10.

My blocks name is from the output in game is:   gemcraft:BlockSapphireOre      meta 0

In the config if I enter:   gemcraft:BlockSapphireOre@0 #vein          
When I try to begin minecraft it then crashes on client loading when fml tries to fire up wtfcore I think,  maybe I'm just a broken record and if I am I apologize I have so little knowledge of Java to understand the crash log.

Any help would be great I'm at the end of my rope on this one!

**Comment by WhiskyTangoFawks** [comment]
If the crash log is the same, then that is what is happening.  I'll have a look and see what I can do to improve the crash logging in terms of getting you a bit more information on what is going on.

**Comment by 0Navis0** [comment]
I think I get the same crash. https://pastebin.com/TJ4ccL7T

**Comment by Viakanr** [comment]
I get the same crash has anyone figured this out? 
Heres my config
https://pastebin.com/gs0J2wtU

**Comment by WenXin20** [comment]
On line 22, the id is spelled 'ailcraft:ore_metal@4 #vein' instead of 'railcraft:ore_metal@4 #vein'. So its just because of a spelling mistake.

**Comment by Viakanr** [comment]
still crashed after i fixed it
https://pastebin.com/xN4xga4G

**Comment by WenXin20** [comment]
If its an ore that this mod can't find, the latest.log should say what is causing the crash. If that's not it, then I'm not sure what it is, and you'll just have to wait for WhiskyTangoFox to reply.
